package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.remoteParameters.hashiCorpVaultParameter
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        add {
            hashiCorpVaultParameter {
                name = "COSIGN_PASSWORD"
                query = "s"
                vaultId = "Vault"
                param("buildTypeId", "DevopsGurdip_DevopsGurdipPortfolio_Build")
            }
        }
        add {
            hashiCorpVaultParameter {
                name = "COSIGN_KEY"
                query = "kv/data/COSIGN_KEY!/key"
                vaultId = "Vault"
            }
        }
    }
}
