package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.HashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.hashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<HashiCorpVaultConnection> {
            hashiCorpVaultConnection {
                id = "Vault"
                name = "HashiCorp Vault (2)"
                vaultNamespace = "DevOps/Portfolio"
                url = "http://vaultdev.gssira.com:8200"
                authMethod = appRole {
                    roleId = "a3076e49-1172-7beb-d487-344ab7cd384c"
                    secretId = "credentialsJSON:490b0b4d-874c-4cca-90f9-933c5f05cfd7"
                }
            }
        }
        feature1.apply {
            authMethod = appRole {
                endpointPath = "approle"
                roleId = "a3076e49-1172-7beb-d487-344ab7cd384c"
                secretId = "credentialsJSON:81b25e05-f1eb-4444-8469-7e669091460b"
            }
            param("teamcity.vault.requirement", "")
            param("gcp-endpoint-path", "")
        }
    }
}
