package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComGurdipSCodeDevopsCiScriptsRefsHeadsMain'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComGurdipSCodeDevopsCiScriptsRefsHeadsMain")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComGurdipSCodeDevopsCiScriptsRefsHeadsMain")
        name = "https://github.com/GurdipSCode/devops-ci-scripts#refs/heads/main"
        url = "https://github.com/GurdipSCode/devops-ci-scripts"
        branch = "refs/heads/main"
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_d928835e688af7380f1585b923074b93:-1:5b66000b-2ac2-4f6b-8c54-020d9b519620"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        agentCleanPolicy = GitVcsRoot.AgentCleanPolicy.ALWAYS
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
    }

}
