package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'PortfolioGitMain1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("PortfolioGitMain1")
    name = "PortfolioGitMain (1)"
    url = "https://github.com/GurdipSCode/devops-gurdip-portfolio"
    branch = "main"
    agentCleanPolicy = GitVcsRoot.AgentCleanPolicy.ALWAYS
    checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
    authMethod = password {
        userName = "GurdipS5"
        password = "credentialsJSON:a1bd6d47-b7ee-43b4-a77f-82c70e9a3313"
    }
}))

